services:
  # 1. Jembatan IoT (Mosquitto MQTT Broker)
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      # file config sederhana agar mosquitto menerima koneksi dari luar
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # 2. DATABASE (MySQL)
  db:
    image: mysql:8.0
    container_name: aquasafe_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAMA}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASS}
      TZ: Asia/Jakarta
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  # 3. PANEL ADMIN DATABASE (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: aquasafe_pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: aquasafe_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
      - mqtt
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=aquasafe_iot

  frontend:
    image: nginx:alpine
    container_name: aquasafe_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html

  motioneye:
    image: ccrisan/motioneye:master-amd64
    container_name: aquasafe_cctv
    ports:
      - "8765:8765"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./motioneye/conf:/etc/motioneye
      - ./motioneye/video:/var/lib/motioneye
    restart: always
