# Konfigurasi MQTT Standar (Buat tes di dalam NUC/Laptop)
listener 1883
allow_anonymous true

# Konfigurasi MQTT over WebSockets (Ini yang dicolok ke Cloudflare!)
listener 9001
protocol websockets
allow_anonymous true